config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :images 

  get 'prueba', to: 'prueba#metodoprueba'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :picture, PictureUploader

	validates :description, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_devise_params, if: :devise_controller?


  def configure_devise_params
  	devise_parameter_sanitizer.permit(:sign_up) do |user|
  		user.permit(:name, :email, :password, :password_confirmation)
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		@images = Image.paginate(page: params[:page], per_page: 6)
  						.order(id: :desc)
  						.where user_id: current_user.id
  	end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: [:show, :edit, :update, :destroy]
	def index
		
	end


	def new
		@image = Image.new

	end

	def create
		@image = current_user.images.new image_params
		
		if @image.save
			return redirect_to images_path
		end

		render :new

	end

	def show
	end

	def edit 
	end

	def update
		@image.update image_params
		redirect_to @image
	end

	def destroy
		@image.destroy
		redirect_to images_path
	end





	private

	def image_params
		params.require(:image).permit :description, :picture
	end

	def set_image
		@image = Image.find params[:id]
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

	
	<div class="row">
		<div class="col-4">
			
		</div>
		<div class="col-8">
			<h1><%= current_user.name %> </h1>
			<div>
				<ul class="nav">
					<li class="margin-right">
						<p> <strong><%= @images.count %></strong> Publicaciones</p>
					</li>
					<li class="margin-right">
						<p> <strong>300</strong> Seguidores</p>
					</li>
					<li class="margin-right">
						<p> <strong>220</strong> Seguidos</p>
					</li>
				</ul>
			</div>
			
		</div>		
	</div>

	<div class="row" id="images">
		<%= render @images %>

	</div>
	<%= will_paginate @images %>
<% else %>

	<h1>RailsGram</h1>

<% end %>

 

app/views/home/index.js.erb
$('#images').append('<%= j render @images %>')

<% if @images.next_page %>
	$('.pagination').replaceWith('<%= j will_pagination @images %>')
<%else%>
	$('.pagination').remove();
<%end%>

app/views/images/_form.html.erb
	<div class="form-group">
		<%= form_for @image, builder: CustomFormBuilder do |f| %>
			<%= f.form_error %>


			<%= f.label :description %><br>
			<%= f.text_field :description, class: 'form-control'%>
			<%= f.field_error :description%>
			<br>
			<%= f.label :picture %><br>
			<%= f.file_field :picture,  class: 'form-control'%>
			<br>
			<%= f.submit 'Guardar', :class => 'btn btn-primary'%>

		<%end %>
	</div>

app/views/images/_image.html.erb
<div class="col-4">
	<figure class="figure">
	  <%= image_tag image.picture.medium.url, class: 'figure-img img-fluid rounded' %>
		<figcaption class="figure-caption"><%= image.description %> 
			<%= link_to t('.edit_link'), edit_image_path(image)%> 
			<%= link_to t('.remove_link'), image, method: :delete, data: {confirm: 'sure?'} %>
		</figcaption>
	</figure>
</div>


<br>


 

app/views/images/edit.html.erb
<div class="container">
	<p>Editar Imagen</p>

<%= render 'form'%>
</div>

app/views/images/index.html.erb
<div class="container">
	<div class="row">
		<%= render @images %>
	</div>
</div>

app/views/images/new.html.erb
<div class="container">
	<p>Crear Imagen</p>

<%= render 'form'%>
</div>

app/views/images/show.html.erb
<%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul class="nav justify-content-end">
      <%- if user_signed_in?%>
        <li class="nav-item">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Iniciar ', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to ' Registrarse', new_user_registration_path, class: "nav-link" %>
          </li>
      <%end%>
    </ul>

  	<div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  		<%= yield %>
  	</div>
    
  </body>
</html>